services:
  laravel:
    build:
      dockerfile: .docker/dockerfile.prod
      target: final
      args:
        - WWWUSER=${WWWUSER}
        - WWWGROUP=${WWWGROUP}
    env_file: .env
    volumes:
      - '.:/var/www/html:rw'
      - '.docker/nginx.conf:/etc/nginx/nginx.conf:ro'
      - '.docker/nginx.vhost.conf:/etc/nginx/conf.d/default.conf:ro'
      #- './database/database.sqlite:/var/www/html/database/database.sqlite:rw'
    extra_hosts:
        - 'host.docker.internal:host-gateway'
    ports:
      - '127.0.0.1:8081:80'
    environment:
        IGNITION_LOCAL_SITES_PATH: '${PWD}'
    depends_on:
      - mariadb
    restart: always

  mariadb:
      image: mariadb:11.5.2
      environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
      #ports:
      #  - "127.0.0.1:3306:3306"
      volumes:
        - mariadb:/var/lib/mysql:rw
      restart: always

volumes:
    mariadb:
