services:
  laravel:
    build:
      dockerfile: .docker/dockerfile.prod
      target: final
    env_file: .env.prod
    volumes:
      - '.:/var/www/html'
      - '.docker/nginx.conf:/etc/nginx/nginx.conf:ro'
      - '.docker/nginx.vhost.conf:/etc/nginx/conf.d/default.conf:ro'
    extra_hosts:
        - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:80'
    environment:
        WWWUSER: '${WWWUSER}'
        IGNITION_LOCAL_SITES_PATH: '${PWD}'
